// Module list and registry are generated by build.rs from the files in this
// directory. Do not add `mod` lines by hand — drop a new <name>.rs in and it is
// discovered, hashed, and registered automatically.
include!(concat!(env!("OUT_DIR"), "/alphas_gen.rs"));
